### ISSUE TITLE
[TODO] Web UI

### ISSUE THREAD

**Issue by zhovner** [Flipper-Zero/flipperzero-remote-testbench-front#2]
Нам нужно:

* ~~Заменить MJPEG видеопоток на тот, что сейчас на сайте lab.flipperzero.one. Там размещено демо html5 видео на плеере flv.js~~ Done.
* Видео с экраном должно размещаться в под прозрачной png картинкой корпуса флиппера. 
* Кнопки должны нажиматься на джойстике как [здесь ](https://www.figma.com/proto/lpCz8WRKnowKhC4pkWiwol/Flipper?node-id=4%3A3530&viewport=1018%2C226%2C0.3916662037372589&scaling=min-zoom) 
* Кнопками можно управлять с клавиатуры: курсор (вверх, вниз, влево, вправо), пробел — центральная кнопка, backspace — кнопка назад
* Отображение статусного светодиода (приходит по SSE)
* Логи внизу должны разделяться по категориям, чтобы можно было выбрать одну категорию, все сразу или любую другую комбинацию. Логи (события) приходят по SSE в JSON уже помеченные.

## Авторизация

* Без авторизации люди не могут нажимать кнопки и загружать файл прошивки, могут только смотреть.

Черновой эскиз страницы, которая в итоге должна быть по адресу lab.flipperzero.one: 

![image](https://user-images.githubusercontent.com/774290/95238524-4da49f80-0812-11eb-84be-34a0180c0176.png)

**UPD:**

* Отправка файла - просто отправляем файл через POST.
* Строка внизу под полем с логами - просто строка текста, передаем как есть через POST.
* Еще раз про авторизацию: Для начала подойдет вариант, когда авторизованному человеку будет приходить ссылка, оканчивающаяся на /?key=DEADBEEF. Фронт передает это значение с каждым нажатием кнопки, отправкой строки и загрузкой файла.

**Comment by psydvl** [comment]
Непонятно насчет авторизации : почему не на беке? 
Также: 
- Только десктоп или mobile friendly тоже? 
- Логи писать пока открыт сайт или брать с внешнего источника?

**Comment by Konfuze** [comment]
> Без авторизации люди не могут нажимать кнопки, только смотреть

А как производится авторизация?

**Comment by otopba** [comment]
То есть, будет какое-то API для получения логов, нажатия кнопок и т.п.?

**Comment by zhovner** [comment]
@psydvl 

> Непонятно насчет авторизации : почему не на беке?

Потому что бек это маленькое устройство, оно не переварит зрителей пытающихся нажимать кнопки. И канал между raspberry pi и сервером тонкий.

> * Только десктоп или mobile friendly тоже?

Только десктоп, мобилы пусть будут криво 

> * Логи писать пока открыт сайт или брать с внешнего источника?

@Konfuze 

> А как производится авторизация?

Не знаю, хоть файлик на сервере фронтенда с логинами и http-auth

>Для макета понадобятся ещё стейты, как минимум, загрузка файла с результатом

Не понимаю 

>Логи категоризируются на сервере или нужно "понять" на фронте, к какой категории они относятся?

На сервере, могут прилетать обернутые по категориям.

**Comment by tobbymarshall815** [comment]
Запросы которые пишутся в “type here” уходят на бэкенд по POST запросам и ответ возвращается оттуда же?

Логи приходят с пометкой фильтра?

При Upload файл просто уходит на бэкенд, верно?

Авторизация должна быть на фронтэнде?

«Кнопки должны нажиматься на джойстике как здесь» имеется ввиду синяя рамка вокруг кнопок?

Есть макет страницы с картинками/шрифтами и тд?

**Comment by imShara** [comment]
Что делает "Upload code"?
Мобильная версия?
Поддержка браузерами?

**Comment by lomalkin** [comment]
> Непонятно насчет авторизации : почему не на беке?

На беке тоже. Все нажатия кнопок и т.д. сопровождаются передачей некоего ключа с фронта

> Также:
> 
>     * Только десктоп или mobile friendly тоже?

Предположу, что смотреть желательно и с мобильноых, нажимать - скорее всего только с компа. Лучше уточнить у @zhovner 

>     * Логи писать пока открыт сайт или брать с внешнего источника?

Только пока открыт сайт.

**Comment by lomalkin** [comment]
>     1. А как производится авторизация?
ответил выше, передаем ключ с фронта

>     2. Как должен работать инпут ">Type here"?
Нужно передать эту строку на сервер, как есть, снабдив тем же ключом авторизации, что и для кнопок (строка).

>     3. Для макета понадобятся ещё стейты, как минимум, загрузка файла с результатом
Если можно, прошу уточнить

>     4. Логи категоризируются на сервере или нужно "понять" на фронте, к какой категории они относятся?
Логи с сервера приходят уже помеченные. Все будет приходить в json.

**Comment by lomalkin** [comment]
> Запросы которые пишутся в “type here” уходят на бэкенд по POST запросам и ответ возвращается оттуда же?
да, уходят и в общем все (ну будет ответ типа все ок). в основном реагируем на то, что придет через SSE.

> Логи приходят с пометкой фильтра?
да

> При Upload файл просто уходит на бэкенд, верно?
да, все так. еще точнее - файл и текстовое поле (адрес загрузки прошивки) - строка с константой

> Авторизация должна быть на фронтэнде?
выше есть про это. передаем ключ и все.

> «Кнопки должны нажиматься на джойстике как здесь» имеется ввиду синяя рамка вокруг кнопок?

> Есть макет страницы с картинками/шрифтами и тд?
@zhovner

**Comment by lomalkin** [comment]
> Что делает "Upload code"?

Грузит файл на сервер, про это выше ответил.

> Мобильная версия?

В идеале, чтобы работало на "только посмотреть", если будет получаться. Управлять/загружать файл не обязательно.

> Поддержка браузерами?

Десктопные версии популярных браузеров. Без излишеств.

**Comment by lomalkin** [comment]
Обновил описание.

**Comment by imShara** [comment]
Пока как-то так https://imshara.github.io/FlipperLab/
@zhovner , @lomalkin накиньте HTTPS на сервер с потоком, из-за mixed content стрим не работает, а гитхаб не даёт отключить https

![Peek 2020-10-07 07-15](https://user-images.githubusercontent.com/4913196/95286825-0ac3e580-086d-11eb-8d30-2dad11e87fb0.gif)

SVG шку дербанить разрешаю
